### ISSUE TITLE
Notifiers documentation is wrong

### ISSUE THREAD

**Issue by parabuzzle** [meskyanichi/backup#602]
In the documentation for using a notifier looks like this:

```ruby
notify_by DataDog do |datadog|
  datadog.on_success           = true
  datadog.on_warning           = true
  datadog.on_failure           = true

   datadog.api_key              = 'api_key'
end
```

however this results in an error like this:

```
[2014/10/24 22:32:46][error] NameError: uninitialized constant Backup::Config::DSL::DataDog
```

Instead you need to define your notifiers like this:

```ruby
notify_by Notifier::DataDog do |datadog|
  datadog.on_success           = true
  datadog.on_warning           = true
  datadog.on_failure           = true

   datadog.api_key              = 'api_key'
end
```

This appears to be the case for all the extended notifiers documented here: http://meskyanichi.github.io/backup/v4/notifiers

We either need to update the docs to reflect the namespace requirement of update the notify_by to include the namespace.

**Comment by tombruijn** [comment]
Closed by #642
