### ISSUE TITLE
Innobackupex stops streaming after 3.2GB

### ISSUE THREAD

**Issue by barttenbrinke** [meskyanichi/backup#617]
The command executed by backup is this:

      sh -c "{ { /usr/bin/innobackupex --user=root --password='REPLACED' --host='localhost' --port='3306'  --no-timestamp /var/rails/backup/shared/tmp/core_mysql_snapshot/databases/MySQL-core2.bkpdir  && /usr/bin/innobackupex --apply-log /var/rails/backup/shared/tmp/core_mysql_snapshot/databases/MySQL-core2.bkpdir --use-memory=4G   && /bin/tar --remove-files -cf -  -C /var/rails/backup/shared/tmp/core_mysql_snapshot/databases MySQL-core2.bkpdir 2>&4 ; echo \"0|$?:\" >&3 ; } | { /bin/gzip 2>&4 ; echo \"1|$?:\" >&3 ; } | { /bin/cat > '/var/rails/backup/shared/tmp/core_mysql_snapshot/databases/MySQL-core2.tar.gz' 2>&4 ; echo \"2|$?:\" >&3 ; } } 3>&1 1>&2 4>&2"

If I do this in a bash console, it works as expected. If I trigger this via a backup action, the backup process grinds to a halt while performing the snapshot: 

      /usr/bin/innobackupex --user=root --password='REPLACED' --host='localhost' --port='3306'  --no-timestamp /var/rails/backup/shared/tmp/core_mysql_snapshot/databases/MySQL-core2.bkpdir

It hangs when about 3.2 GB is transferred and I see no progress in file size/top/whatsoever. Is there some way for me to debug this further?

**Comment by barttenbrinke** [comment]
Maybe put this workaround somewhere in the documentation and leave it with that for now.

**Comment by taf2** [comment]
I was having this same issue.  turning verbose = false seems to have solved the problem for me.
