### ISSUE TITLE
Add support for explicit SSL FTP storage

### ISSUE THREAD

**Issue by jgornick** [meskyanichi/backup#621]
Currently the FTP storage doesn't support FTP servers that are configured with explicit SSL. Would it be possible to change the FTP library for the FTP storage that uses a library with support for explicit (or implicit) SSL? 

I found this library, but am not familiar with it: https://github.com/bnix/double-bag-ftps

**Comment by tombruijn** [comment]
hi @jgornick, the maintainers aren't currently planning to add new features in the near future. Any new feature will have to come from the community.

If you're up for it you can create a PR adding explicit SSL support for the FTP storage option. However, I can see that the double-bag-ftps library won't be allowed as a dependency. It should be attempted to add it to the Storage::FTP class with minimal impact.

I'll close the issue, if you want to pick it up please send in a PR. If not, I recommend creating an issue on the [backup-features](https://github.com/meskyanichi/backup-features/issues/) repo.
