### ISSUE TITLE
Net::FTPTempError: 426 Transfer aborted.  Data connection closed.

### ISSUE THREAD

**Issue by noff** [meskyanichi/backup#622]
Using FTP as storage.

Config: 

```
   Storage::FTP.defaults do |server|
    server.username   = "..."
    server.password   = "..."
    server.ip         = "..."
    server.port       = 21
    server.path       = "..."
    server.keep       = 5
    server.passive_mode = true
  end
```

Today 4 tryouts of backup crushed with error:
```Net::FTPTempError: 426 Transfer aborted.  Data connection closed.```

Manual connection to FTP and working using FTP client do well. FTP server stable and always availably.

gem version 4.1.2
backup size 1Gb
split size 100Mb

**Comment by tombruijn** [comment]
hi @noff, I don't have any problems here? Did this suddenly start occurring or is this a new setup?
If it was running before did you update anything? Either the ruby version, backup gem or packages on the server?

**Comment by noff** [comment]
Hi.
It suddenly start occurring this Friday. Updated from 4.1.2 to 4.1.5 - same problem. Contacted with hoster - their trying to define problems on their side but no success.
Ruby 2.1.5. Current gem version 4.1.5 (last).

**Comment by tombruijn** [comment]
@noff  So the problem occurred before you updated?

It would be unlikely that it would just stop working.

**Comment by noff** [comment]
Hi. Solved by storage hosting company. 
But may be need some feature to prolong "waiting time" if connection "halt" and reconnecting on dropped connection.
