### ISSUE TITLE
Dropbox absoulate path error

### ISSUE THREAD

**Issue by toufiqueimam** [meskyanichi/backup#625]
In the /lib/backup/storage/dropbox.rb file line 59 is removing the first character of the storage path. So absoulate link path does not work. For example if I set db.path        = "/path/to/my/backups" It will read as
~/path/to/my/backups But It does not store the file there either and fails to upload. I had to set db.path        = "//path/to/my/backups" (needed to use double slash) to set the proper absoulate path

**Comment by tombruijn** [comment]
Closed in favor of #626
