### ISSUE TITLE
Activesupport 4.2 Support

### ISSUE THREAD

**Issue by dannytip** [meskyanichi/backup#629]
Backup depends on thread_safe 0.1.3 but rails/activesupport 4.2 require >= 0.3.4

**Comment by tombruijn** [comment]
Hi @dannytip. Are you by any chance using the same bundle (Gemfile) for your backup configuration and Rails application?

If so, this is not recommended and not supported. Please separate the configuration between the two and try again.

For more information see this thread, starting from my comment, linked:  https://github.com/meskyanichi/backup/pull/620#issuecomment-68487077

Let me know if my assumption was wrong, I'll reopen the issue if you describe your setup more clearly.
