### ISSUE TITLE
Postgres, Backup each schema separately

### ISSUE THREAD

**Issue by ivanstojkovicapps** [meskyanichi/backup#630]
Hi,

is there a way to backup schemas and store them in separate files instead of backup up the whole database?

regards Ivan

**Comment by bmaeser** [comment]
why did you close this issue?
is there a pragmatic way to do this without configuring each schema separately?

**Comment by tombruijn** [comment]
It should be possible by using the `additional_options` option on the [pg database config](http://meskyanichi.github.io/backup/v4/database-postgresql/). Use the [--schema-only](http://www.postgresql.org/docs/9.1/static/app-pgdump.html) option to not export the data in the schemas.

I'm afraid you'll have to configure multiple models with `database PostgreSQL` blocks to export them to separate files.
