### ISSUE TITLE
bup storage support?

### ISSUE THREAD

**Issue by fullofcaffeine** [meskyanichi/backup#634]
https://github.com/bup/bup looks really interesting. Perhaps it makes sense to add it as a Backup Storage?

**Comment by tombruijn** [comment]
Currently the team isn't looking to add new features to backup. If you want to add support you can submit a PR with an implementation.

If you're unable to create a PR I suggest creating an issue on the [backup-features issue tracker](https://github.com/meskyanichi/backup-features/issues). There new features for a future major version are listed/things other people can pick up.

**Comment by dmitry** [comment]
@fullofcaffeine would you like to collaborate to create a patch? I'm using bup on two servers to backup information and send it to the main backup storage. Let me know, we can chat and implement the feature and propose it as a PR.

**Comment by fullofcaffeine** [comment]
Hi @dmitry, I barely played with `bup`, but found the concept very nice at the time. Haven't looked into it lately, might look into it again. At the time my only backup solution was a custom `backup gem` setup that would copy everything to an external drive, pretty primitive. I honestly decided to simplify this aspect of my computing life for now and bought `Arq`, which `just works` (great).

How has been your experience with bup when it comes to backuping and restoring data? Depending on valuable bup would be to backup my servers, yes, I could consider spending some time on creating a patch.

**Comment by dmitry** [comment]
@fullofcaffeine one of the servers have 3M of static files with size of 500GB + MySQL and redis databases, it takes ~2 hours to backup all of them. I think it's very fast (it could be faster, but still it's good enough). Once I required to restore a MySQL database schema, and it was more or less easy to do. With bup it's possible to use `git checkout` :) I've looked for different solutions, and bup I found good enough. What is lack - there are no encryption, but I don't need it, at least for those projects I'm using it. 

My resume - it's good tool for small/medium size projects. There are no automatic tools to restore static/database, all must be done manually, but still it's gives you at least some guarantee, if your production system become dead, and you have transferred all the data while backup process to the other host (and it's alive) - you can restore everything in 6-12 hours without excuses :)
