### ISSUE TITLE
Why is it not recommended to use this gem with bundler?

### ISSUE THREAD

**Issue by groe** [meskyanichi/backup#635]
I have read that the backup gem is an **application distributed as a gem**, but not a **library** - and therefore it is not recommended to use it in application `Gemfile`s with bundler.

However, I could not find any reasoning about that. I am wondering why that is the case?

My use case: I have several independent web applications hosted on the same or different servers. Each of these applications is deployed with capistrano from a git repository, which is pretty much self-contained, e.g. the deployment script (re)starts background jobs and sets up cronjobs with `whenever`. Up to now I was doing backups with manually managed crontab entries and rsync, but now I am considering to use the backup gem for each of these applications via the `Gemfile` and to include it in the `whenever` schedules for each application individually. That way I would have all the app configuration, including backup settings and schedules, directly in the application repository itself.

Is this considered a bad practice with the backup gem? If so, why?

**Comment by meskyanichi** [comment]
Have you seen the [runtime dependencies](https://rubygems.org/gems/backup)? :trollface:

**Comment by tombruijn** [comment]
@groe I explained it here  https://github.com/meskyanichi/backup/pull/620#issuecomment-68524048 quite recently. Hope that helps. But yeah. I don't think you want 40-something gems in memory of your Rails app if it's only used for your backups.

If you have any other questions, let me know.

**Comment by meskyanichi** [comment]
Memory shouldn't be an issue since you can just add them to another group to avoid loading them in runtime. However, it will cause a truckload of **dependency conflicts** regardless of which group you place them in. By adding Backup to your Gemfile, you're essentially either **constraining** your actual runtime dependencies' versions, or **preventing** your dependencies from resolving at all due to the version conflicts.

**Comment by groe** [comment]
Thanks for clarifying that, @meskyanichi and @tombruijn! A few words about that in the docs (or even a link to this issue) could make that more obvious for others as well.

So I image a good setup could be like that: Install the backup gem in the `global` gemset of RVM, do *not* add it in individual project gemfiles but use the backup command in the projects `whenever` schedule anyway as it should be available from the global gemset, right?

**Comment by meskyanichi** [comment]
You could do that. Also, while I haven't tried it, I'd imagine you can just drop a `Gemfile` in the Backup directory where your configuration files live and have Bundler take care of dependency resolution.

I'm pretty sure that you can run `bundle exec backup [args]` from the Crontab to have bundler ensure that the right version of your dependencies are loaded in. I've personally never used Backup on a multi-purpose server, so I've never had to deal with version conflicts. I'd say it's worth a shot to see if that's possible. Saves you the hassle of maintaining gemsets and what not, especially when you pull down updates.

**Comment by groe** [comment]
Thanks! Keep up the great work!

**Comment by meskyanichi** [comment]
No problem. ;)

**Comment by tombruijn** [comment]
@groe @meskyanichi I updated the installation page on the docs to explain more clearly that installation shouldn't be done in a Rails application's Gemfile. https://github.com/meskyanichi/backup/commit/70b1f445e1eeb830fc71fceb3b859550674125d9

I hope this is more clear. Maybe we should another couple lines on the whole dependency conflict issue? See issue #637. Rails 4.2.0 and backup in the same gemfile will install version 3.4.0 instead of 4.x

**Comment by groe** [comment]
:+1:

**Comment by habermann24** [comment]
Since the backup gem does not work as soon as newer gem version of its dependencies are installed in the same global gemset, how about generating the following content for the "bin/backup" script file (just like in the gemspec):

```ruby
#!/usr/bin/env ruby
# encoding: utf-8

# Gem Dependencies
# Generated by `rake gemspec`. Do Not Edit.
gem 'CFPropertyList', '= 2.3.1'
gem 'addressable', '= 2.3.5'
gem 'atomic', '= 1.1.14'
gem 'aws-ses', '= 0.5.0'
gem 'buftok', '= 0.2.0'
gem 'builder', '= 3.2.2'
gem 'descendants_tracker', '= 0.0.3'
gem 'dogapi', '= 1.11.0'
gem 'dropbox-sdk', '= 1.5.1'
gem 'equalizer', '= 0.0.9'
gem 'excon', '= 0.44.4'
gem 'faraday', '= 0.8.8'
gem 'fission', '= 0.5.0'
gem 'flowdock', '= 0.4.0'
gem 'fog', '= 1.28.0'
gem 'fog-atmos', '= 0.1.0'
gem 'fog-aws', '= 0.1.1'
gem 'fog-brightbox', '= 0.7.1'
gem 'fog-core', '= 1.29.0'
gem 'fog-ecloud', '= 0.0.2'
gem 'fog-json', '= 1.0.0'
gem 'fog-profitbricks', '= 0.0.2'
gem 'fog-radosgw', '= 0.0.3'
gem 'fog-riakcs', '= 0.1.0'
gem 'fog-sakuracloud', '= 1.0.0'
gem 'fog-serverlove', '= 0.1.1'
gem 'fog-softlayer', '= 0.4.1'
gem 'fog-storm_on_demand', '= 0.1.0'
gem 'fog-terremark', '= 0.0.4'
gem 'fog-vmfusion', '= 0.0.1'
gem 'fog-voxel', '= 0.0.2'
gem 'fog-xml', '= 0.1.1'
gem 'formatador', '= 0.2.5'
gem 'hipchat', '= 1.0.1'
gem 'http', '= 0.5.0'
gem 'http_parser.rb', '= 0.6.0'
gem 'httparty', '= 0.12.0'
gem 'inflecto', '= 0.0.2'
gem 'ipaddress', '= 0.8.0'
gem 'json', '= 1.8.2'
gem 'mail', '= 2.5.4'
gem 'memoizable', '= 0.4.0'
gem 'mime-types', '= 1.25.1'
gem 'mini_portile', '= 0.6.2'
gem 'multi_json', '= 1.10.1'
gem 'multi_xml', '= 0.5.5'
gem 'multipart-post', '= 1.2.0'
gem 'net-scp', '= 1.2.1'
gem 'net-sftp', '= 2.1.2'
gem 'net-ssh', '= 2.9.2'
gem 'nokogiri', '= 1.6.6.2'
gem 'open4', '= 1.3.0'
gem 'pagerduty', '= 2.0.0'
gem 'polyglot', '= 0.3.3'
gem 'simple_oauth', '= 0.2.0'
gem 'thor', '= 0.18.1'
gem 'thread_safe', '= 0.1.3'
gem 'treetop', '= 1.4.15'
gem 'twitter', '= 5.5.0'
gem 'unf', '= 0.1.3'
gem 'unf_ext', '= 0.0.6'
gem 'xml-simple', '= 1.1.4'

require File.expand_path("../../lib/backup", __FILE__)
Backup::CLI.start
```

This would make sure people could still install some other command line gem and not break the backup dependencies. I'm running into this problem because the "foreman" gem installs thor 0.19.1...therefore, the backup gem conflicts.

This would solve such issues.

Would this be a proper solution? If yes, I could provide a pull-request.

**Comment by tombruijn** [comment]
Hi @habermann24, thanks for the suggestion. But wouldn't bundler do the same thing? Do you call backup with bundler? If not, please do so.

**Comment by neohunter** [comment]
This is still very confusing, I suggest adding a new wiki entry explaining how to setup it FOR a rails project, for example, the backup.rb  configuration file should be on the app repository even if it's not installed with bundle, not on the homepath.

**Comment by Xosmond** [comment]
Use it separately on another folder with bundler.

**Comment by texasecb** [comment]
Would you mind sharing what you would suggest in terms of running the backup gem on a server, it's very clear from the above that it shouldn't be added to the application's gemfile, but it's not particularly clear what a better approach would be?

If someone has a Rails application with their gems in a gemfile, is the advice: to create a completely new rails application just containing the backup gem; to install the gem via `gem install backup` within the application's directory (and potentially create a new gemfile); or something else?

Appreciate this is probably a dumb question, but I'm sure a clear steer from an experienced Rails developer would be very useful for lots of people trying to use this gem or similar
