### ISSUE TITLE
Feature: Ruby friendly interface

### ISSUE THREAD

**Issue by rafaelsales** [meskyanichi/backup#636]
I didn't find this in the documentation, but I found useful sometimes to call backup gem from ruby. If there was an interface class, maybe using same options available in the CLI, would solve the problem.

E.g.
```ruby
begin 
  Backup.perform(trigger: :adwords_backup, 
                 config_file: File.join(%w(backup config.rb)),
                 env: { "BACKUP_ENV" => Rails.env })
rescue Backup::Error => e
  MyNotificationProvider.notify(e)
end
```

**Comment by rafaelsales** [comment]
I can try to develop this and submit a PR if you guys find useful.

**Comment by tombruijn** [comment]
Hi @rafaelsales, I've never really had to use it directly from Ruby. I would just "shell out" and run the command. Can you describe a use case where you would load in the "Backup" ecosystem in another app? This is something we're already discouraging in the docs, in combination with a Rails app for example.

Currently we're not looking to expand the feature set as such. The team is only doing maintenance on version 4 at the moment. Taking community PRs to add new features or support other systems. I wouldn't even really know how much work this would take. I assume it's a matter of taking certain logic out of Backup::CLI and making it accessible from a more generic class and let CLI and the "Control" class communicate with it.

I'll close this issue in **this** issue tracker. If you're (not) going to work on it (now) I suggest creating another issue on the [features issue tracker](https://github.com/meskyanichi/backup-features/issues) and discuss any ideas there. Ping me there if you want to.
