### ISSUE TITLE
add Google Cloud Storage / nearline to storages

### ISSUE THREAD

**Issue by bmaeser** [meskyanichi/backup#639]
in march 2015 google introduced the Cloud Storage / Nearline plattform.
using this service as a backup-storage would make a great improvement to this project.
regards, Bernhard

http://googlecloudplatform.blogspot.co.at/2015/03/introducing-Google-Cloud-Storage-Nearline-near-online-data-at-an-offline-price.html

**Comment by cristiangauma** [comment]
+1

**Comment by cristiangauma** [comment]
+1

But for what I've just read, I think the feature requests tracker is this one: https://github.com/meskyanichi/backup-features

We should open an issue there to ask for this feature. @bmaeser do you want to do it (as you are the OP)?

**Comment by bmaeser** [comment]
ah, didn't see that, thanks for pointing it out @cristiangauma .
issue moved to meskyanichi/backup-features#22 , i am closing this one.
